# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import smart_home_pb2 as smart__home__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in smart_home_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SmartHomeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListDevices = channel.unary_unary(
                '/smartHome.SmartHomeService/ListDevices',
                request_serializer=smart__home__pb2.ListDevicesRequest.SerializeToString,
                response_deserializer=smart__home__pb2.ListDevicesResponse.FromString,
                _registered_method=True)
        self.GetDeviceInfo = channel.unary_unary(
                '/smartHome.SmartHomeService/GetDeviceInfo',
                request_serializer=smart__home__pb2.DeviceInfoRequest.SerializeToString,
                response_deserializer=smart__home__pb2.DeviceInfoResponse.FromString,
                _registered_method=True)
        self.ControlDevice = channel.unary_unary(
                '/smartHome.SmartHomeService/ControlDevice',
                request_serializer=smart__home__pb2.ControlRequest.SerializeToString,
                response_deserializer=smart__home__pb2.ControlResponse.FromString,
                _registered_method=True)
        self.MonitorDevice = channel.unary_stream(
                '/smartHome.SmartHomeService/MonitorDevice',
                request_serializer=smart__home__pb2.MonitorRequest.SerializeToString,
                response_deserializer=smart__home__pb2.DeviceStatus.FromString,
                _registered_method=True)


class SmartHomeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListDevices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDeviceInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ControlDevice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MonitorDevice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SmartHomeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListDevices': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDevices,
                    request_deserializer=smart__home__pb2.ListDevicesRequest.FromString,
                    response_serializer=smart__home__pb2.ListDevicesResponse.SerializeToString,
            ),
            'GetDeviceInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDeviceInfo,
                    request_deserializer=smart__home__pb2.DeviceInfoRequest.FromString,
                    response_serializer=smart__home__pb2.DeviceInfoResponse.SerializeToString,
            ),
            'ControlDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.ControlDevice,
                    request_deserializer=smart__home__pb2.ControlRequest.FromString,
                    response_serializer=smart__home__pb2.ControlResponse.SerializeToString,
            ),
            'MonitorDevice': grpc.unary_stream_rpc_method_handler(
                    servicer.MonitorDevice,
                    request_deserializer=smart__home__pb2.MonitorRequest.FromString,
                    response_serializer=smart__home__pb2.DeviceStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'smartHome.SmartHomeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('smartHome.SmartHomeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SmartHomeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListDevices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smartHome.SmartHomeService/ListDevices',
            smart__home__pb2.ListDevicesRequest.SerializeToString,
            smart__home__pb2.ListDevicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDeviceInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smartHome.SmartHomeService/GetDeviceInfo',
            smart__home__pb2.DeviceInfoRequest.SerializeToString,
            smart__home__pb2.DeviceInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ControlDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smartHome.SmartHomeService/ControlDevice',
            smart__home__pb2.ControlRequest.SerializeToString,
            smart__home__pb2.ControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MonitorDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/smartHome.SmartHomeService/MonitorDevice',
            smart__home__pb2.MonitorRequest.SerializeToString,
            smart__home__pb2.DeviceStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
